### ISSUE TITLE
Displayed P/L is incorrectly based on offer price

### ISSUE THREAD

**Issue by scratchscratchscratchy** [itchysats/frontend#2]
![image](https://user-images.githubusercontent.com/5557790/140003406-6001df44-33d0-4ad1-9372-4ae1cb1fde2a.png)

The P/L and profit amount calculation is based on the price of the current offer of the maker, and not on the actual price feed (that is used by the oracle for attestation as well).
This paints a wrong picture of what is going on in all CFDs.

I think using the maker offer price as the price to be displayed is also disputable - it does not reflect the price that is used for the payout distribution and is misleading. I think we have to model this closer to the UI that was created by the comit guys.

**Comment by 1010Tom** [comment]
Seems to be correct: the value is taken from what we get back from the backend. 
The only calculation we do in the frontend is rounding it: https://github.com/itchysats/frontend/blob/feac715919f67cd8dc80e3deba26ec6ee6a426cf/src/components/History.tsx#L78

**Comment by 1010Tom** [comment]
Note: what might be confusing and can be changed is that it is rounded.
